apiVersion: v1
kind: Service
metadata:
  name: {{ include "locust.fullname" . }}-scheduler
  labels:
    {{- include "locust.labels" . | nindent 4 }}
    component: scheduler
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: web
    - port: 5557
      targetPort: 5557
      protocol: TCP
      name: sched-bind
    - port: 5558
      targetPort: 5558
      protocol: TCP
      name: sched-bind-2
  selector:
    {{- include "locust.selectorLabels" . | nindent 4 }}
    component: scheduler